language: java
jdk:
  -openjdk11
os:
  - linux

# https://docs.travis-ci.com/user/languages/java/#caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# https://docs.travis-ci.com/user/customizing-the-build/#safelisting-or-blocklisting-branches
branches:
  only:
    - master